spring.datasource.url=jdbc:postgresql://10.94.117.154:5432/package?
spring.datasource.username=dn101187pov
spring.datasource.password=dfdbkjy1987ukraine
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=2000MB
spring.servlet.multipart.max-request-size=2000MB


